/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query Anime(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n    $genreIn: [String]\n    $genreNotIn: [String]\n    $sort: [MediaSort]\n    $format: MediaFormat\n    $status: MediaStatus\n    $isAdult: Boolean\n    $search: String\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(\n        type: $type\n        status_in: $statusIn\n        genre_in: $genreIn\n        genre_not_in: $genreNotIn\n        sort: $sort\n        format: $format\n        status: $status\n        isAdult: $isAdult\n        search: $search\n      ) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n      pageInfo {\n        total\n        perPage\n        currentPage\n        lastPage\n        hasNextPage\n      }\n    }\n  }\n": typeof types.AnimeDocument,
    "\n  query AnimeGenre(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n    $genreIn: [String]\n    $genreNotIn: [String]\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(\n        type: $type\n        status_in: $statusIn\n        genre_in: $genreIn\n        genre_not_in: $genreNotIn\n      ) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n      pageInfo {\n        total\n        perPage\n        currentPage\n        lastPage\n        hasNextPage\n      }\n    }\n  }\n": typeof types.AnimeGenreDocument,
    "\n  query AnimeDetails($mediaId: Int) {\n    Media(id: $mediaId) {\n      bannerImage\n      averageScore\n      coverImage {\n        large\n        extraLarge\n      }\n      description\n      episodes\n      endDate {\n        year\n        month\n        day\n      }\n      format\n      genres\n      id\n      popularity\n      startDate {\n        year\n        month\n        day\n      }\n      status\n      title {\n        english\n        romaji\n        native\n      }\n      type\n    }\n  }\n": typeof types.AnimeDetailsDocument,
    "\n  query Page(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(type: $type, status_in: $statusIn) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n    }\n  }\n": typeof types.PageDocument,
    "\n  query AnimeSearch($search: String!) {\n    Page {\n      media(search: $search, type: ANIME) {\n        id\n        title {\n          romaji\n          english\n          native\n        }\n        sort: meanScore\n      }\n    }\n  }\n": typeof types.AnimeSearchDocument,
};
const documents: Documents = {
    "\n  query Anime(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n    $genreIn: [String]\n    $genreNotIn: [String]\n    $sort: [MediaSort]\n    $format: MediaFormat\n    $status: MediaStatus\n    $isAdult: Boolean\n    $search: String\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(\n        type: $type\n        status_in: $statusIn\n        genre_in: $genreIn\n        genre_not_in: $genreNotIn\n        sort: $sort\n        format: $format\n        status: $status\n        isAdult: $isAdult\n        search: $search\n      ) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n      pageInfo {\n        total\n        perPage\n        currentPage\n        lastPage\n        hasNextPage\n      }\n    }\n  }\n": types.AnimeDocument,
    "\n  query AnimeGenre(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n    $genreIn: [String]\n    $genreNotIn: [String]\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(\n        type: $type\n        status_in: $statusIn\n        genre_in: $genreIn\n        genre_not_in: $genreNotIn\n      ) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n      pageInfo {\n        total\n        perPage\n        currentPage\n        lastPage\n        hasNextPage\n      }\n    }\n  }\n": types.AnimeGenreDocument,
    "\n  query AnimeDetails($mediaId: Int) {\n    Media(id: $mediaId) {\n      bannerImage\n      averageScore\n      coverImage {\n        large\n        extraLarge\n      }\n      description\n      episodes\n      endDate {\n        year\n        month\n        day\n      }\n      format\n      genres\n      id\n      popularity\n      startDate {\n        year\n        month\n        day\n      }\n      status\n      title {\n        english\n        romaji\n        native\n      }\n      type\n    }\n  }\n": types.AnimeDetailsDocument,
    "\n  query Page(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(type: $type, status_in: $statusIn) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n    }\n  }\n": types.PageDocument,
    "\n  query AnimeSearch($search: String!) {\n    Page {\n      media(search: $search, type: ANIME) {\n        id\n        title {\n          romaji\n          english\n          native\n        }\n        sort: meanScore\n      }\n    }\n  }\n": types.AnimeSearchDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Anime(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n    $genreIn: [String]\n    $genreNotIn: [String]\n    $sort: [MediaSort]\n    $format: MediaFormat\n    $status: MediaStatus\n    $isAdult: Boolean\n    $search: String\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(\n        type: $type\n        status_in: $statusIn\n        genre_in: $genreIn\n        genre_not_in: $genreNotIn\n        sort: $sort\n        format: $format\n        status: $status\n        isAdult: $isAdult\n        search: $search\n      ) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n      pageInfo {\n        total\n        perPage\n        currentPage\n        lastPage\n        hasNextPage\n      }\n    }\n  }\n"): (typeof documents)["\n  query Anime(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n    $genreIn: [String]\n    $genreNotIn: [String]\n    $sort: [MediaSort]\n    $format: MediaFormat\n    $status: MediaStatus\n    $isAdult: Boolean\n    $search: String\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(\n        type: $type\n        status_in: $statusIn\n        genre_in: $genreIn\n        genre_not_in: $genreNotIn\n        sort: $sort\n        format: $format\n        status: $status\n        isAdult: $isAdult\n        search: $search\n      ) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n      pageInfo {\n        total\n        perPage\n        currentPage\n        lastPage\n        hasNextPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AnimeGenre(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n    $genreIn: [String]\n    $genreNotIn: [String]\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(\n        type: $type\n        status_in: $statusIn\n        genre_in: $genreIn\n        genre_not_in: $genreNotIn\n      ) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n      pageInfo {\n        total\n        perPage\n        currentPage\n        lastPage\n        hasNextPage\n      }\n    }\n  }\n"): (typeof documents)["\n  query AnimeGenre(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n    $genreIn: [String]\n    $genreNotIn: [String]\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(\n        type: $type\n        status_in: $statusIn\n        genre_in: $genreIn\n        genre_not_in: $genreNotIn\n      ) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n      pageInfo {\n        total\n        perPage\n        currentPage\n        lastPage\n        hasNextPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AnimeDetails($mediaId: Int) {\n    Media(id: $mediaId) {\n      bannerImage\n      averageScore\n      coverImage {\n        large\n        extraLarge\n      }\n      description\n      episodes\n      endDate {\n        year\n        month\n        day\n      }\n      format\n      genres\n      id\n      popularity\n      startDate {\n        year\n        month\n        day\n      }\n      status\n      title {\n        english\n        romaji\n        native\n      }\n      type\n    }\n  }\n"): (typeof documents)["\n  query AnimeDetails($mediaId: Int) {\n    Media(id: $mediaId) {\n      bannerImage\n      averageScore\n      coverImage {\n        large\n        extraLarge\n      }\n      description\n      episodes\n      endDate {\n        year\n        month\n        day\n      }\n      format\n      genres\n      id\n      popularity\n      startDate {\n        year\n        month\n        day\n      }\n      status\n      title {\n        english\n        romaji\n        native\n      }\n      type\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Page(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(type: $type, status_in: $statusIn) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  query Page(\n    $page: Int\n    $perPage: Int\n    $type: MediaType\n    $statusIn: [MediaStatus]\n  ) {\n    Page(page: $page, perPage: $perPage) {\n      media(type: $type, status_in: $statusIn) {\n        id\n        genres\n        coverImage {\n          medium\n          large\n          extraLarge\n        }\n        title {\n          english\n          native\n          romaji\n        }\n        status\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AnimeSearch($search: String!) {\n    Page {\n      media(search: $search, type: ANIME) {\n        id\n        title {\n          romaji\n          english\n          native\n        }\n        sort: meanScore\n      }\n    }\n  }\n"): (typeof documents)["\n  query AnimeSearch($search: String!) {\n    Page {\n      media(search: $search, type: ANIME) {\n        id\n        title {\n          romaji\n          english\n          native\n        }\n        sort: meanScore\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;